using System.Reflection;
using System.Text;
using ShukujitsuSharp;

Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

var client = new HttpClient();
var bytes = await client.GetByteArrayAsync("https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv");
var csv = Encoding.GetEncoding("shift_jis").GetString(bytes);
var allShukujitsu = csv
    .Split(Environment.NewLine)
    .Skip(1) // Skip header
    .Where(x => !string.IsNullOrEmpty(x)) // Skip the last empty line
    .Select(x => x.Split(","))
    .Select(x => new Shukujitsu(DateOnly.Parse(x[0]), x[1].Replace("\r", ""))); // Remove "CR"

var builder = new StringBuilder();
using var writer = new StringWriter(builder) { NewLine = "\n" };

writer.WriteLine("""
    // Code generated by ShukujitsuSharp.Generator; DO NOT EDIT.
    namespace ShukujitsuSharp;
    
    public partial class Shukujitsu
    {
        public static IEnumerable<Shukujitsu> Dates => new List<Shukujitsu>
        {
    """);

foreach (var item in allShukujitsu)
{
    writer.WriteLine(@$"        new Shukujitsu(new DateOnly({item.Date.Year}, {item.Date.Month}, {item.Date.Day}), ""{item.Name}""),");
}

writer.WriteLine("""
        };
    }
    """);

var exe = Assembly.GetAssembly(typeof(Program))?.Location!;
var data = Path.Combine(Directory.GetParent(exe)!.Parent!.Parent!.Parent!.Parent!.FullName!, "ShukujitsuSharp/ShukujitsuData.cs");
await File.WriteAllTextAsync(data, builder.ToString());
