using System.Text;
using ShukujitsuSharp;

Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

var client = new HttpClient();
var bytes = await client.GetByteArrayAsync("https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv");
var csv = Encoding.GetEncoding("shift_jis").GetString(bytes);
var aaa = csv
    .Split(Environment.NewLine)
    .Skip(1) // Skip header
    .Where(x => !string.IsNullOrEmpty(x)) // Skip the last empty line
    .Select(x => x.Split(","))
    .Select(x => new Shukujitsu(DateOnly.Parse(x[0]), x[1]));

var builder = new StringBuilder();
builder.Append(@"// Code generated by ShukujitsuSharp.Generator; DO NOT EDIT.
namespace ShukujitsuSharp;

public partial class Shukujitsu
{
    public static IEnumerable<Shukujitsu> Dates => new List<Shukujitsu>
    {
");

foreach (var item in aaa)
{
    builder.AppendLine(@$"        new Shukujitsu(new DateOnly({item.Date.Year}, {item.Date.Month}, {item.Date.Day}), ""{item.Name}""),");
}

builder.Remove(builder.Length - 1, 1);
builder.Append(@"
    };
}
");

await File.WriteAllTextAsync("src/ShukujitsuSharp/ShukujitsuData.cs", builder.ToString());
