name: check-update

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Update
      run: |
        dotnet run --project ./src/ShukujitsuSharp.Generator
        git diff --exit-code --quiet && exit
        git add -A
        git config --global user.name SIkebe
        git config --global user.email SIkebe@users.noreply.github.com
        git commit -m "Update ShukujitsuData.cs"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Update ShukujitsuData.cs

