name: check-update

permissions: write-all

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        include-prerelease: true
    - name: Update
      run: |
        dotnet run --project ./src/ShukujitsuSharp.Generator
        if ! git diff --exit-code --quiet
        then
          git status
          git add -A
          git config user.name SIkebe
          git config user.email SIkebe@users.noreply.github.com
          git commit -m "Update ShukujitsuData.cs"
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update ShukujitsuData.cs

