name: CI

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Commit updated files
      run: |
        git config core.filemode false
        dotnet run --project ./src/ShukujitsuSharp.Generator
        if ! git diff --exit-code --quiet
        then
          git add -A
          git config user.name github-actions
          git config user.email action@github.com
          git commit -m "Update ShukujitsuData.cs"
          git push
        fi
