name: CI

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Update
      run: |
        dotnet run --project ./src/ShukujitsuSharp.Generator
        if ! git diff --exit-code --quiet
        then
          git status
          git add -A
          git config user.name SIkebe
          git config user.email SIkebe@users.noreply.github.com
          git commit -m "Update ShukujitsuData.cs"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}}
        fi
