name: CI

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - if: github.event_name != 'pull_request' 
      uses: actions/checkout@v2
    - if: github.event_name == 'pull_request' 
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Update
      run: |
        dotnet run --project ./src/ShukujitsuSharp.Generator
        if ! git diff --exit-code --quiet
        then
          git add -A
          git config user.name SIkebe
          git config user.email SIkebe@users.noreply.github.com
          git commit -m "Update ShukujitsuData.cs"
        fi
    - if: github.event_name == 'pull_request'
      name: Git push
      run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}}
    - if: github.event_name != 'pull_request' 
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update ShukujitsuData.cs
        token: ${{ secrets.GITHUB_TOKEN }}
